"""Skrócona lista spółek (głównie large-cap US) do szybkiego skanowania — nie pełny S&P 500.

Pełne pokrycie rynku USA wymaga zewnętrznego feedu (np. plik CSV / API płatne). Tutaj: reprezentatywny
zbiór ~60 tickerów płynnych; użytkownik może nadpisać listę w żądaniu API.
"""

from __future__ import annotations

DEFAULT_US_LIQUID_TICKERS: tuple[str, ...] = (
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK-B",
    "UNH",
    "JNJ",
    "V",
    "XOM",
    "JPM",
    "PG",
    "MA",
    "HD",
    "CVX",
    "MRK",
    "ABBV",
    "PEP",
    "COST",
    "KO",
    "AVGO",
    "WMT",
    "MCD",
    "CSCO",
    "ACN",
    "TMO",
    "ABT",
    "CRM",
    "ADBE",
    "NFLX",
    "DIS",
    "AMD",
    "INTC",
    "QCOM",
    "TXN",
    "IBM",
    "ORCL",
    "NOW",
    "INTU",
    "AMAT",
    "LRCX",
    "MU",
    "PYPL",
    "UBER",
    "SHOP",
    "SNOW",
    "PANW",
    "CRWD",
    "ZS",
    "DDOG",
    "NET",
    "MDB",
    "COIN",
    "HOOD",
    "SOFI",
    "PLTR",
    "RIVN",
    "LCID",
    "F",
    "GM",
    "BA",
    "CAT",
    "GE",
)
